[workspace]

resolver = "2"

members = [
    "modules",
    "relayer",
    "relayer-cli",
    "relayer-rest",
    "telemetry",
    "proto",
    "tools/integration-test",
    "tools/test-framework",
]

exclude = [
    "ci/no-std-check",
    "proto-compiler"
]

[patch.crates-io]
tendermint              = { git = "https://github.com/informalsystems/tendermint-rs", branch = "mikhail/allow-omitted-fields-in-abci_info" }
tendermint-rpc          = { git = "https://github.com/informalsystems/tendermint-rs", branch = "mikhail/allow-omitted-fields-in-abci_info" }
tendermint-proto        = { git = "https://github.com/informalsystems/tendermint-rs", branch = "mikhail/allow-omitted-fields-in-abci_info" }
tendermint-light-client = { git = "https://github.com/informalsystems/tendermint-rs", branch = "mikhail/allow-omitted-fields-in-abci_info" }
tendermint-light-client-verifier = { git = "https://github.com/informalsystems/tendermint-rs", branch = "mikhail/allow-omitted-fields-in-abci_info" }
tendermint-testgen      = { git = "https://github.com/informalsystems/tendermint-rs", branch = "mikhail/allow-omitted-fields-in-abci_info" }
