[package]
name = "ibc-proxy"
version = "0.1.0"
edition = "2021"

# let's make sure enough debug information is included so
# that we get source file / line numbers info in our stacktraces
[profile.release]
debug = 1

[dependencies]
async-stream = "0.3.3"
axum = { version = "0.5.4", features = ["json"] }
clap = { version = "3.1.15", features = ["derive"] }
color-eyre = "0.6.1"
flex-error = { version = "0.4.4", features = ["eyre_tracer"], default-features = false }
futures = "0.3.21"
hyper = { version = "0.14.18", features = ["client", "http1"] }
ibc = "0.15.0"
itertools = "0.10.3"
prost = "0.10.3"
serde = "1.0.137"
serde_json = "1.0.81"
sqlx = { version = "0.5.13", features = ["runtime-tokio-rustls", "postgres", "time"] }
# subtle-encoding = "0.5.1"
tendermint = "0.23.7"
tendermint-proto = "0.23.7"
tendermint-rpc = { version = "0.23.7", features = ["websocket-client"] }
time = "0.2.27"
tokio = { version = "1.18.1", features = ["full"] }
tower = "0.4.12"
tower-http = { version = "0.3.2", features = ["trace"] }
tracing = "0.1.34"
tracing-error = "0.2.0"
tracing-subscriber = { version = "0.3.11", features = ["env-filter"] }

[patch.crates-io]
tendermint = { git = "https://github.com/informalsystems/tendermint-rs", branch = "romac/ibc-proxy" }
tendermint-proto = { git = "https://github.com/informalsystems/tendermint-rs", branch = "romac/ibc-proxy" }
tendermint-rpc = { git = "https://github.com/informalsystems/tendermint-rs", branch = "romac/ibc-proxy" }
