[global]
log-level = 'trace'

[mode]

[mode.clients]
enabled = true
refresh = true
misbehaviour = true

[mode.connections]
enabled = false

[mode.channels]
enabled = false

[mode.packets]
enabled = true
clear-interval = 100
clear-on-start = true
tx-confirmation = true

[telemetry]
enabled = false
host = '127.0.0.1'
port = 3001

[[chains]]
id = 'ibc-0'
rpc-addr = 'http://ibc-0:26657'
grpc-addr = 'http://ibc-0:9090'
websocket-addr = 'ws://ibc-0:26657/websocket'
rpc-timeout = '10s'
account-prefix = 'cosmos'
key-name = 'testkey'
store-prefix = 'ibc'
max-gas = 3000000
max-msg-num = 30
max-tx-size = 2097152
gas-price = { price = 0.001, denom = 'stake' }
clock-drift = '5s'
trusting-period = '14days'
trust-threshold = { numerator = '1', denominator = '3' }

[[chains]]
id = 'ibc-1'
rpc-addr = 'http://ibc-1:26657'
grpc-addr = 'http://ibc-1:9090'
websocket-addr = 'ws://ibc-1:26657/websocket'
rpc-timeout = '10s'
account-prefix = 'cosmos'
key-name = 'testkey'
store-prefix = 'ibc'
max-gas = 3000000
max-msg-num = 30
max-tx-size = 2097152
gas-price = { price = 0.001, denom = 'stake' }
clock-drift = '5s'
trusting-period = '14days'
trust-threshold = { numerator = '1', denominator = '3' }
